import type { CardIllustration, ComprehensionCard, LanguageCode, QuestionRound, QuestionSkill } from '../types.ts'
import { pickWeighted, type ProblemStatsMap } from './scores.ts'

type LocalizedText = { en: string } & Partial<Record<LanguageCode, string>>

interface CardTemplate {
  id: string
  skill: QuestionSkill
  title: LocalizedText
  categoryLabel: LocalizedText
  illustration: CardIllustration
  passage: LocalizedText
  question: LocalizedText
  correctAnswer: LocalizedText
  wrongAnswer: LocalizedText
}

const TITLES = {
  mainIdea: {
    en: 'Main Idea',
    es: 'Idea principal',
    fr: 'Idee principale',
    de: 'Hauptidee',
    pt: 'Ideia principal',
    hi: 'मुख्य विचार',
  },
  details: {
    en: 'Key Detail',
    es: 'Detalle clave',
    fr: 'Detail important',
    de: 'Wichtiges Detail',
    pt: 'Detalhe importante',
    hi: 'मुख्य विवरण',
  },
  sequence: {
    en: 'What Happens Next',
    es: 'Que pasa despues',
    fr: 'Que se passe-t-il ensuite',
    de: 'Was passiert als Nachstes',
    pt: 'O que acontece depois',
    hi: 'आगे क्या होगा',
  },
  inference: {
    en: 'Make an Inference',
    es: 'Haz una inferencia',
    fr: 'Fais une inference',
    de: 'Schlussfolgere',
    pt: 'Faca uma inferencia',
    hi: 'अनुमान लगाओ',
  },
  conclusion: {
    en: 'Draw a Conclusion',
    es: 'Saca una conclusion',
    fr: 'Tire une conclusion',
    de: 'Ziehe eine Schlussfolgerung',
    pt: 'Tire uma conclusao',
    hi: 'निष्कर्ष निकालो',
  },
  feelings: {
    en: 'Feelings and Motives',
    es: 'Sentimientos y razones',
    fr: 'Sentiments et raisons',
    de: 'Gefuhle und Grunde',
    pt: 'Sentimentos e motivos',
    hi: 'भावनाएं और कारण',
  },
  riddles: {
    en: 'Riddles',
    es: 'Adivinanzas',
    fr: 'Devinettes',
    de: 'Ratsel',
    pt: 'Adivinhas',
    hi: 'पहेलियां',
  },
  patterns: {
    en: 'Pattern Puzzles',
    es: 'Patrones',
    fr: 'Suites et formes',
    de: 'Muster Puzzles',
    pt: 'Padroes',
    hi: 'पैटर्न पहेलियां',
  },
  logic: {
    en: 'Logic Clues',
    es: 'Pistas de logica',
    fr: 'Indices logiques',
    de: 'Logik Hinweise',
    pt: 'Pistas de logica',
    hi: 'तर्क संकेत',
  },
  challenge: {
    en: 'Challenge Mix',
    es: 'Mezcla desafio',
    fr: 'Melange defi',
    de: 'Challenge Mix',
    pt: 'Mistura desafio',
    hi: 'चुनौती मिश्रण',
  },
} satisfies Record<string, LocalizedText>

const CATEGORIES = {
  stories: {
    en: 'Stories',
    es: 'Historias',
    fr: 'Histoires',
    de: 'Geschichten',
    pt: 'Historias',
    hi: 'कहानियां',
  },
  closeRead: {
    en: 'Close Reading',
    es: 'Lectura atenta',
    fr: 'Lecture attentive',
    de: 'Genau lesen',
    pt: 'Leitura atenta',
    hi: 'ध्यान से पढ़ो',
  },
  clues: {
    en: 'Story Clues',
    es: 'Pistas',
    fr: 'Indices',
    de: 'Hinweise',
    pt: 'Pistas',
    hi: 'संकेत',
  },
  feelings: {
    en: 'Characters',
    es: 'Personajes',
    fr: 'Personnages',
    de: 'Figuren',
    pt: 'Personagens',
    hi: 'चरित्र',
  },
  puzzles: {
    en: 'Puzzles',
    es: 'Rompecabezas',
    fr: 'Puzzles',
    de: 'Puzzles',
    pt: 'Quebra-cabecas',
    hi: 'पहेलियां',
  },
  logic: {
    en: 'Logic',
    es: 'Logica',
    fr: 'Logique',
    de: 'Logik',
    pt: 'Logica',
    hi: 'तर्क',
  },
  challenge: {
    en: 'Challenge',
    es: 'Desafio',
    fr: 'Defi',
    de: 'Challenge',
    pt: 'Desafio',
    hi: 'चुनौती',
  },
} satisfies Record<string, LocalizedText>

const LEVEL_LABELS: Record<number, LocalizedText> = {
  1: TITLES.mainIdea,
  2: TITLES.details,
  3: TITLES.sequence,
  4: TITLES.inference,
  5: TITLES.conclusion,
  6: TITLES.feelings,
  7: TITLES.riddles,
  8: TITLES.patterns,
  9: TITLES.logic,
  10: TITLES.challenge,
}

const LEVELS_DATA: Record<number, CardTemplate[]> = {
  1: [
    {
      id: 'l1-garden',
      skill: 'main-idea',
      title: TITLES.mainIdea,
      categoryLabel: CATEGORIES.stories,
      illustration: 'story',
      passage: {
        en: 'Mia plants seeds in small cups by the window. Every morning she gives them water and turns the cups toward the sun.',
        es: 'Mia planta semillas en vasos pequenos junto a la ventana. Cada manana les pone agua y gira los vasos hacia el sol.',
        fr: 'Mia plante des graines dans de petits pots pres de la fenetre. Chaque matin, elle les arrose et tourne les pots vers le soleil.',
        de: 'Mia pflanzt Samen in kleine Becher am Fenster. Jeden Morgen gibt sie ihnen Wasser und dreht die Becher zur Sonne.',
        pt: 'Mia planta sementes em copinhos perto da janela. Todas as manhas ela coloca agua e vira os copos para o sol.',
        hi: 'मिया खिड़की के पास छोटे कपों में बीज लगाती है। हर सुबह वह उन्हें पानी देती है और कपों को सूरज की ओर घुमाती है।',
      },
      question: {
        en: 'What is this mostly about?',
        es: 'De que trata principalmente?',
        fr: 'De quoi parle surtout ce texte ?',
        de: 'Worum geht es hier hauptsachlich?',
        pt: 'Sobre o que e este texto principalmente?',
        hi: 'यह पैसेज मुख्य रूप से किस बारे में है?',
      },
      correctAnswer: {
        en: 'Mia is taking care of growing plants.',
        es: 'Mia esta cuidando plantas que estan creciendo.',
        fr: 'Mia prend soin de plantes qui poussent.',
        de: 'Mia kummert sich um wachsende Pflanzen.',
        pt: 'Mia esta cuidando de plantas que estao crescendo.',
        hi: 'मिया उग रहे पौधों की देखभाल कर रही है।',
      },
      wrongAnswer: {
        en: 'Mia is looking for a lost toy.',
        es: 'Mia esta buscando un juguete perdido.',
        fr: 'Mia cherche un jouet perdu.',
        de: 'Mia sucht nach einem verlorenen Spielzeug.',
        pt: 'Mia esta procurando um brinquedo perdido.',
        hi: 'मिया एक खोया हुआ खिलौना ढूंढ रही है।',
      },
    },
    {
      id: 'l1-library',
      skill: 'main-idea',
      title: TITLES.mainIdea,
      categoryLabel: CATEGORIES.stories,
      illustration: 'story',
      passage: {
        en: 'The class walks quietly into the library. Students pick books, sit on soft rugs, and read for twenty minutes.',
        es: 'La clase entra en silencio a la biblioteca. Los estudiantes eligen libros, se sientan en alfombras suaves y leen durante veinte minutos.',
        fr: 'La classe entre calmement dans la bibliotheque. Les eleves choisissent des livres, sasssoient sur des tapis doux et lisent pendant vingt minutes.',
        de: 'Die Klasse geht ruhig in die Bibliothek. Die Kinder suchen sich Bucher aus, setzen sich auf weiche Teppiche und lesen zwanzig Minuten.',
        pt: 'A turma entra em silencio na biblioteca. Os alunos escolhem livros, sentam em tapetes macios e leem por vinte minutos.',
        hi: 'कक्षा चुपचाप पुस्तकालय में जाती है। बच्चे किताबें चुनते हैं, मुलायम दरी पर बैठते हैं और बीस मिनट तक पढ़ते हैं।',
      },
      question: {
        en: 'What is this mostly about?',
        es: 'De que trata principalmente?',
        fr: 'De quoi parle surtout ce texte ?',
        de: 'Worum geht es hier hauptsachlich?',
        pt: 'Sobre o que e este texto principalmente?',
        hi: 'यह पैसेज मुख्य रूप से किस बारे में है?',
      },
      correctAnswer: {
        en: 'The class is spending time reading in the library.',
        es: 'La clase esta pasando tiempo leyendo en la biblioteca.',
        fr: 'La classe passe du temps a lire dans la bibliotheque.',
        de: 'Die Klasse verbringt Zeit mit Lesen in der Bibliothek.',
        pt: 'A turma esta passando um tempo lendo na biblioteca.',
        hi: 'कक्षा पुस्तकालय में पढ़ने का समय बिता रही है।',
      },
      wrongAnswer: {
        en: 'The class is getting ready for a loud concert.',
        es: 'La clase se esta preparando para un concierto ruidoso.',
        fr: 'La classe se prepare pour un concert tres bruyant.',
        de: 'Die Klasse bereitet sich auf ein lautes Konzert vor.',
        pt: 'A turma esta se preparando para um show barulhento.',
        hi: 'कक्षा एक तेज़ संगीत कार्यक्रम की तैयारी कर रही है।',
      },
    },
  ],
  2: [
    {
      id: 'l2-lunchbox',
      skill: 'details',
      title: TITLES.details,
      categoryLabel: CATEGORIES.closeRead,
      illustration: 'detail',
      passage: {
        en: 'Sara opens her lunchbox and finds apple slices, a cheese sandwich, and a note from Dad.',
        es: 'Sara abre su lonchera y encuentra rodajas de manzana, un sandwich de queso y una nota de papa.',
        fr: 'Sara ouvre sa boite a lunch et trouve des tranches de pomme, un sandwich au fromage et un mot de son pere.',
        de: 'Sara offnet ihre Brotdose und findet Apfelscheiben, ein Kasesandwich und eine Notiz von Papa.',
        pt: 'Sara abre a lancheira e encontra fatias de maca, um sanduiche de queijo e um bilhete do pai.',
        hi: 'सारा अपना लंचबॉक्स खोलती है और उसमें सेब के टुकड़े, चीज़ सैंडविच और पापा की एक पर्ची पाती है।',
      },
      question: {
        en: 'What was inside Sara\'s lunchbox?',
        es: 'Que habia dentro de la lonchera de Sara?',
        fr: 'Quy avait-il dans la boite de Sara ?',
        de: 'Was war in Saras Brotdose?',
        pt: 'O que havia na lancheira de Sara?',
        hi: 'सारा के लंचबॉक्स के अंदर क्या था?',
      },
      correctAnswer: {
        en: 'A cheese sandwich and apple slices.',
        es: 'Un sandwich de queso y rodajas de manzana.',
        fr: 'Un sandwich au fromage et des tranches de pomme.',
        de: 'Ein Kasesandwich und Apfelscheiben.',
        pt: 'Um sanduiche de queijo e fatias de maca.',
        hi: 'चीज़ सैंडविच और सेब के टुकड़े।',
      },
      wrongAnswer: {
        en: 'A bowl of soup and crackers.',
        es: 'Un tazon de sopa y galletas saladas.',
        fr: 'Un bol de soupe et des biscuits sales.',
        de: 'Eine Schale Suppe und Cracker.',
        pt: 'Uma tigela de sopa e biscoitos.',
        hi: 'एक कटोरी सूप और नमकीन बिस्कुट।',
      },
    },
    {
      id: 'l2-zoo',
      skill: 'details',
      title: TITLES.details,
      categoryLabel: CATEGORIES.closeRead,
      illustration: 'detail',
      passage: {
        en: 'At the zoo, Ava watches the penguins slide into cold water. Later she buys a postcard from the gift shop.',
        es: 'En el zoologico, Ava mira a los pinguinos deslizarse al agua fria. Mas tarde compra una postal en la tienda.',
        fr: 'Au zoo, Ava regarde les pingouins glisser dans leau froide. Plus tard, elle achete une carte postale a la boutique.',
        de: 'Im Zoo sieht Ava zu, wie die Pinguine ins kalte Wasser rutschen. Spater kauft sie eine Postkarte im Laden.',
        pt: 'No zoologico, Ava observa os pinguins deslizarem para a agua fria. Depois ela compra um cartao-postal na loja.',
        hi: 'चिड़ियाघर में आवा पेंगुइनों को ठंडे पानी में फिसलते हुए देखती है। बाद में वह गिफ्ट शॉप से एक पोस्टकार्ड खरीदती है।',
      },
      question: {
        en: 'Which animals did Ava watch?',
        es: 'Que animales miro Ava?',
        fr: 'Quels animaux Ava a-t-elle regardes ?',
        de: 'Welche Tiere hat Ava beobachtet?',
        pt: 'Quais animais Ava observou?',
        hi: 'आवा ने किन जानवरों को देखा?',
      },
      correctAnswer: {
        en: 'Penguins.',
        es: 'Pinguinos.',
        fr: 'Des pingouins.',
        de: 'Pinguine.',
        pt: 'Pinguins.',
        hi: 'पेंगुइन।',
      },
      wrongAnswer: {
        en: 'Lions.',
        es: 'Leones.',
        fr: 'Des lions.',
        de: 'Lowen.',
        pt: 'Leoes.',
        hi: 'शेर।',
      },
    },
  ],
  3: [
    {
      id: 'l3-seed',
      skill: 'sequence',
      title: TITLES.sequence,
      categoryLabel: CATEGORIES.clues,
      illustration: 'sequence',
      passage: {
        en: 'Tara digs a small hole, drops in a seed, and covers it with soil. Then she fills a watering can.',
        es: 'Tara cava un hoyo pequeno, pone una semilla y la cubre con tierra. Luego llena una regadera.',
        fr: 'Tara creuse un petit trou, y met une graine et la recouvre de terre. Ensuite, elle remplit un arrosoir.',
        de: 'Tara grabt ein kleines Loch, legt einen Samen hinein und bedeckt ihn mit Erde. Dann fullt sie eine Gieskanne.',
        pt: 'Tara cava um pequeno buraco, coloca uma semente e cobre com terra. Depois ela enche um regador.',
        hi: 'तारा एक छोटा गड्ढा खोदती है, उसमें बीज डालती है और मिट्टी से ढक देती है। फिर वह पानी देने की कैन भरती है।',
      },
      question: {
        en: 'What will Tara probably do next?',
        es: 'Que hara Tara despues?',
        fr: 'Que fera probablement Tara ensuite ?',
        de: 'Was wird Tara wahrscheinlich als Nachstes tun?',
        pt: 'O que Tara provavelmente fara depois?',
        hi: 'तारा आगे क्या करेगी?',
      },
      correctAnswer: {
        en: 'Water the seed she planted.',
        es: 'Regar la semilla que planto.',
        fr: 'Arroser la graine quelle a plantee.',
        de: 'Den Samen giesen, den sie gepflanzt hat.',
        pt: 'Regar a semente que ela plantou.',
        hi: 'वह लगाए हुए बीज को पानी देगी।',
      },
      wrongAnswer: {
        en: 'Pack the seed into her backpack.',
        es: 'Guardar la semilla en su mochila.',
        fr: 'Mettre la graine dans son sac.',
        de: 'Den Samen in ihren Rucksack packen.',
        pt: 'Guardar a semente na mochila.',
        hi: 'वह बीज को अपने बैग में रख देगी।',
      },
    },
    {
      id: 'l3-suitcase',
      skill: 'sequence',
      title: TITLES.sequence,
      categoryLabel: CATEGORIES.clues,
      illustration: 'sequence',
      passage: {
        en: 'Nora folds shirts, tucks socks into her shoes, and zips up a small suitcase by the front door.',
        es: 'Nora dobla camisas, mete calcetines dentro de sus zapatos y cierra una maleta pequena junto a la puerta.',
        fr: 'Nora plie des chemises, glisse des chaussettes dans ses chaussures et ferme une petite valise pres de la porte.',
        de: 'Nora faltet Hemden, steckt Socken in ihre Schuhe und schliest einen kleinen Koffer an der Haustur.',
        pt: 'Nora dobra camisas, coloca meias dentro dos sapatos e fecha uma pequena mala perto da porta.',
        hi: 'नोरा कमीजें मोड़ती है, मोज़े जूतों के अंदर रखती है और दरवाज़े के पास एक छोटा सूटकेस बंद करती है।',
      },
      question: {
        en: 'What will probably happen next?',
        es: 'Que pasara despues?',
        fr: 'Que va-t-il probablement se passer ensuite ?',
        de: 'Was wird wahrscheinlich als Nachstes passieren?',
        pt: 'O que provavelmente vai acontecer depois?',
        hi: 'आगे क्या होने की सबसे अधिक संभावना है?',
      },
      correctAnswer: {
        en: 'Nora will leave for a trip.',
        es: 'Nora saldra de viaje.',
        fr: 'Nora partira en voyage.',
        de: 'Nora wird auf eine Reise gehen.',
        pt: 'Nora saira para uma viagem.',
        hi: 'नोरा यात्रा पर जाएगी।',
      },
      wrongAnswer: {
        en: 'Nora will plant flowers in the yard.',
        es: 'Nora plantara flores en el patio.',
        fr: 'Nora va planter des fleurs dans le jardin.',
        de: 'Nora wird Blumen im Hof pflanzen.',
        pt: 'Nora vai plantar flores no quintal.',
        hi: 'नोरा आंगन में फूल लगाएगी।',
      },
    },
  ],
  4: [
    {
      id: 'l4-boots',
      skill: 'inference',
      title: TITLES.inference,
      categoryLabel: CATEGORIES.clues,
      illustration: 'inference',
      passage: {
        en: 'Kira stomps into the house with muddy boots and wet sleeves. She is grinning and carrying a tiny shovel.',
        es: 'Kira entra a la casa con botas llenas de barro y mangas mojadas. Sonrie y lleva una pala pequena.',
        fr: 'Kira entre dans la maison avec des bottes boueuses et des manches mouillees. Elle sourit et porte une petite pelle.',
        de: 'Kira stampft mit schlammigen Stiefeln und nassen Armeln ins Haus. Sie grinst und tragt eine kleine Schaufel.',
        pt: 'Kira entra em casa com botas enlameadas e mangas molhadas. Ela esta sorrindo e carregando uma pazinha.',
        hi: 'कीरा घर में कीचड़ भरे जूतों और गीली बांहों के साथ आती है। वह मुस्कुरा रही है और उसके हाथ में एक छोटी फावड़ी है।',
      },
      question: {
        en: 'What was Kira probably doing outside?',
        es: 'Que estaba haciendo Kira afuera?',
        fr: 'Que faisait probablement Kira dehors ?',
        de: 'Was hat Kira wahrscheinlich draussen gemacht?',
        pt: 'O que Kira provavelmente estava fazendo la fora?',
        hi: 'कीरा बाहर क्या कर रही होगी?',
      },
      correctAnswer: {
        en: 'She was playing in the mud.',
        es: 'Estaba jugando en el barro.',
        fr: 'Elle jouait dans la boue.',
        de: 'Sie hat im Schlamm gespielt.',
        pt: 'Ela estava brincando na lama.',
        hi: 'वह कीचड़ में खेल रही थी।',
      },
      wrongAnswer: {
        en: 'She was sitting in a movie theater.',
        es: 'Estaba sentada en un cine.',
        fr: 'Elle etait assise dans un cinema.',
        de: 'Sie sas in einem Kino.',
        pt: 'Ela estava sentada em um cinema.',
        hi: 'वह किसी सिनेमा में बैठी थी।',
      },
    },
    {
      id: 'l4-stage',
      skill: 'inference',
      title: TITLES.inference,
      categoryLabel: CATEGORIES.clues,
      illustration: 'inference',
      passage: {
        en: 'Behind the curtain, Amaya whispers her lines again and again. Her hands shake until she hears her teacher say, "You know this."',
        es: 'Detras de la cortina, Amaya repite sus lineas una y otra vez. Sus manos tiemblan hasta que escucha a su maestra decir: "Tu puedes."',
        fr: 'Derriere le rideau, Amaya repete ses repliques encore et encore. Ses mains tremblent jusqua ce que son enseignante dise : "Tu connais cela."',
        de: 'Hinter dem Vorhang flustert Amaya ihre Zeilen immer wieder. Ihre Hande zittern, bis ihre Lehrerin sagt: "Du kannst das."',
        pt: 'Atras da cortina, Amaya repete suas falas muitas vezes. Suas maos tremem ate ouvir a professora dizer: "Voce sabe fazer isso."',
        hi: 'परदे के पीछे अमाया अपनी पंक्तियां बार-बार धीरे से दोहराती है। उसके हाथ तब तक कांपते रहते हैं जब तक उसकी शिक्षिका नहीं कहती, "तुम यह कर सकती हो।"',
      },
      question: {
        en: 'What can you infer about Amaya?',
        es: 'Que puedes inferir sobre Amaya?',
        fr: 'Que peux-tu deduire sur Amaya ?',
        de: 'Was kannst du uber Amaya schlussfolgern?',
        pt: 'O que voce pode inferir sobre Amaya?',
        hi: 'अमाया के बारे में तुम क्या अनुमान लगा सकते हो?',
      },
      correctAnswer: {
        en: 'She feels nervous before going on stage.',
        es: 'Se siente nerviosa antes de salir al escenario.',
        fr: 'Elle se sent nerveuse avant de monter sur scene.',
        de: 'Sie ist nervos, bevor sie auf die Buhne geht.',
        pt: 'Ela se sente nervosa antes de subir ao palco.',
        hi: 'मंच पर जाने से पहले वह घबराई हुई है।',
      },
      wrongAnswer: {
        en: 'She is bored because nothing is happening.',
        es: 'Esta aburrida porque no pasa nada.',
        fr: 'Elle sennuie parce quil ne se passe rien.',
        de: 'Sie langweilt sich, weil nichts passiert.',
        pt: 'Ela esta entediada porque nada esta acontecendo.',
        hi: 'वह ऊब रही है क्योंकि कुछ हो नहीं रहा है।',
      },
    },
  ],
  5: [
    {
      id: 'l5-shelter',
      skill: 'conclusion',
      title: TITLES.conclusion,
      categoryLabel: CATEGORIES.stories,
      illustration: 'conclusion',
      passage: {
        en: 'On Saturday, the class brought old towels, pet food, and small toys to the animal shelter. They cleaned cages and spent time gently brushing the dogs.',
        es: 'El sabado, la clase llevo toallas viejas, comida para mascotas y juguetes pequenos al refugio de animales. Limpiaron jaulas y cepillaron a los perros con cuidado.',
        fr: 'Samedi, la classe a apporte de vieilles serviettes, de la nourriture pour animaux et de petits jouets au refuge. Ils ont nettoye des cages et brosse les chiens doucement.',
        de: 'Am Samstag brachte die Klasse alte Handtucher, Tierfutter und kleine Spielzeuge ins Tierheim. Sie reinigten Kafige und bursteten die Hunde vorsichtig.',
        pt: 'No sabado, a turma levou toalhas velhas, comida para animais e pequenos brinquedos ao abrigo. Eles limparam as gaiolas e escovaram os cachorros com cuidado.',
        hi: 'शनिवार को कक्षा पुराने तौलिये, पालतू भोजन और छोटे खिलौने पशु आश्रय में लेकर गई। उन्होंने पिंजरे साफ किए और कुत्तों को प्यार से ब्रश किया।',
      },
      question: {
        en: 'What conclusion fits best?',
        es: 'Que conclusion es la mejor?',
        fr: 'Quelle conclusion convient le mieux ?',
        de: 'Welche Schlussfolgerung passt am besten?',
        pt: 'Qual conclusao combina melhor?',
        hi: 'कौन सा निष्कर्ष सबसे सही है?',
      },
      correctAnswer: {
        en: 'The class wanted to help care for animals.',
        es: 'La clase queria ayudar a cuidar animales.',
        fr: 'La classe voulait aider a prendre soin des animaux.',
        de: 'Die Klasse wollte Tieren helfen und sie versorgen.',
        pt: 'A turma queria ajudar a cuidar dos animais.',
        hi: 'कक्षा जानवरों की देखभाल में मदद करना चाहती थी।',
      },
      wrongAnswer: {
        en: 'The class wanted to train for a basketball game.',
        es: 'La clase queria entrenar para un partido de baloncesto.',
        fr: 'La classe voulait sentrainer pour un match de basket.',
        de: 'Die Klasse wollte fur ein Basketballspiel trainieren.',
        pt: 'A turma queria treinar para um jogo de basquete.',
        hi: 'कक्षा बास्केटबॉल खेल की तैयारी करना चाहती थी।',
      },
    },
    {
      id: 'l5-teamwork',
      skill: 'conclusion',
      title: TITLES.conclusion,
      categoryLabel: CATEGORIES.stories,
      illustration: 'conclusion',
      passage: {
        en: 'At first, the tower of blocks kept falling. After talking quietly, the children made a wider base and took turns adding pieces. The final tower stood taller than anyone expected.',
        es: 'Al principio, la torre de bloques se caia una y otra vez. Despues de hablar con calma, los ninos hicieron una base mas ancha y se turnaron para poner piezas. La torre final quedo mas alta de lo esperado.',
        fr: 'Au debut, la tour de blocs tombait sans cesse. Apres avoir parle calmement, les enfants ont fait une base plus large et ont ajoute les pieces chacun leur tour. La tour finale etait plus haute que prevu.',
        de: 'Zuerst fiel der Turm aus Bauklotzen immer wieder um. Nachdem die Kinder ruhig gesprochen hatten, bauten sie eine breitere Basis und setzten abwechselnd Steine darauf. Der fertige Turm war hoher als erwartet.',
        pt: 'No inicio, a torre de blocos caia o tempo todo. Depois de conversar com calma, as criancas fizeram uma base mais larga e colocaram as pecas em turnos. A torre final ficou mais alta do que todos esperavam.',
        hi: 'शुरू में ब्लॉकों का टावर बार-बार गिर रहा था। शांति से बात करने के बाद बच्चों ने चौड़ा आधार बनाया और बारी-बारी से टुकड़े जोड़े। आखिर का टावर सबकी उम्मीद से ऊंचा खड़ा रहा।',
      },
      question: {
        en: 'What conclusion fits best?',
        es: 'Que conclusion es la mejor?',
        fr: 'Quelle conclusion convient le mieux ?',
        de: 'Welche Schlussfolgerung passt am besten?',
        pt: 'Qual conclusao combina melhor?',
        hi: 'कौन सा निष्कर्ष सबसे सही है?',
      },
      correctAnswer: {
        en: 'Working together helped the children succeed.',
        es: 'Trabajar juntos ayudo a los ninos a tener exito.',
        fr: 'Travailler ensemble a aide les enfants a reussir.',
        de: 'Gemeinsames Arbeiten half den Kindern, Erfolg zu haben.',
        pt: 'Trabalhar juntos ajudou as criancas a conseguir sucesso.',
        hi: 'मिलकर काम करने से बच्चों को सफलता मिली।',
      },
      wrongAnswer: {
        en: 'The children gave up because the blocks were too hard.',
        es: 'Los ninos se rindieron porque los bloques eran muy dificiles.',
        fr: 'Les enfants ont abandonne parce que les blocs etaient trop difficiles.',
        de: 'Die Kinder gaben auf, weil die Klotze zu schwer waren.',
        pt: 'As criancas desistiram porque os blocos eram dificeis demais.',
        hi: 'बच्चों ने हार मान ली क्योंकि ब्लॉक बहुत कठिन थे।',
      },
    },
  ],
  6: [
    {
      id: 'l6-bike',
      skill: 'feelings',
      title: TITLES.feelings,
      categoryLabel: CATEGORIES.feelings,
      illustration: 'feelings',
      passage: {
        en: 'After weeks of practice, Elena finally rode her bike without training wheels. Her little brother ran beside her, shouting, "You did it!" while Elena laughed all the way to the mailbox.',
        es: 'Despues de semanas de practica, Elena por fin monto su bicicleta sin ruedas de apoyo. Su hermanito corrio a su lado gritando: "Lo lograste" mientras Elena reia hasta el buzon.',
        fr: 'Apres des semaines dentrainement, Elena a enfin fait du velo sans petites roues. Son petit frere courait a cote delle en criant : "Tu las fait !" pendant quelle riait jusqua la boite aux lettres.',
        de: 'Nach Wochen des Ubens fuhr Elena endlich ohne Stutzrader Fahrrad. Ihr kleiner Bruder lief neben ihr her und rief: "Du hast es geschafft!", wahrend Elena bis zum Briefkasten lachte.',
        pt: 'Depois de semanas de pratica, Elena finalmente andou de bicicleta sem rodinhas. Seu irmao menor correu ao lado dela gritando: "Voce conseguiu!" enquanto Elena ria ate a caixa de correio.',
        hi: 'कई हफ्तों के अभ्यास के बाद एलेना आखिरकार बिना सहायक पहियों के साइकिल चला पाई। उसका छोटा भाई उसके साथ दौड़ते हुए चिल्लाया, "तुमने कर दिखाया!" और एलेना हंसते हुए डाकपेटी तक गई।',
      },
      question: {
        en: 'How is Elena most likely feeling?',
        es: 'Como se siente Elena probablemente?',
        fr: 'Comment Elena se sent-elle probablement ?',
        de: 'Wie fuhlt sich Elena wahrscheinlich?',
        pt: 'Como Elena provavelmente esta se sentindo?',
        hi: 'एलेना कैसा महसूस कर रही होगी?',
      },
      correctAnswer: {
        en: 'Proud and excited.',
        es: 'Orgullosa y emocionada.',
        fr: 'Fier et enthousiaste.',
        de: 'Stolz und aufgeregt.',
        pt: 'Orgulhosa e animada.',
        hi: 'गर्वित और उत्साहित।',
      },
      wrongAnswer: {
        en: 'Embarrassed and worried.',
        es: 'Avergonzada y preocupada.',
        fr: 'Genee et inquiete.',
        de: 'Verlegen und besorgt.',
        pt: 'Envergonhada e preocupada.',
        hi: 'शर्मिंदा और चिंतित।',
      },
    },
    {
      id: 'l6-sandwich',
      skill: 'feelings',
      title: TITLES.feelings,
      categoryLabel: CATEGORIES.feelings,
      illustration: 'feelings',
      passage: {
        en: 'At lunch, Mateo noticed that his new classmate had forgotten her food. He split his sandwich in half and pushed the larger piece toward her.',
        es: 'En el almuerzo, Mateo noto que su nueva companera habia olvidado su comida. Partio su sandwich por la mitad y le acerco la parte mas grande.',
        fr: 'Au dejeuner, Mateo a remarque que sa nouvelle camarade avait oublie son repas. Il a coupe son sandwich en deux et lui a pousse la plus grande part.',
        de: 'Beim Mittagessen bemerkte Mateo, dass seine neue Mitschulerin ihr Essen vergessen hatte. Er teilte sein Sandwich und schob ihr das grossere Stuck zu.',
        pt: 'No almoco, Mateo percebeu que sua nova colega havia esquecido a comida. Ele dividiu o sanduiche ao meio e empurrou a parte maior para ela.',
        hi: 'दोपहर के भोजन पर माटेओ ने देखा कि उसकी नई सहपाठी अपना खाना भूल गई है। उसने अपना सैंडविच दो हिस्सों में बांटा और बड़ा हिस्सा उसकी ओर बढ़ा दिया।',
      },
      question: {
        en: 'Why did Mateo share his sandwich?',
        es: 'Por que Mateo compartio su sandwich?',
        fr: 'Pourquoi Mateo a-t-il partage son sandwich ?',
        de: 'Warum hat Mateo sein Sandwich geteilt?',
        pt: 'Por que Mateo compartilhou seu sanduiche?',
        hi: 'माटेओ ने अपना सैंडविच क्यों बांटा?',
      },
      correctAnswer: {
        en: 'He wanted to help someone who had no lunch.',
        es: 'Queria ayudar a alguien que no tenia almuerzo.',
        fr: 'Il voulait aider quelquun qui navait pas de repas.',
        de: 'Er wollte jemandem helfen, der kein Mittagessen hatte.',
        pt: 'Ele queria ajudar alguem que nao tinha almoco.',
        hi: 'वह ऐसे व्यक्ति की मदद करना चाहता था जिसके पास दोपहर का खाना नहीं था।',
      },
      wrongAnswer: {
        en: 'He did not like sandwiches anymore.',
        es: 'Ya no le gustaban los sandwiches.',
        fr: 'Il naimait plus les sandwiches.',
        de: 'Er mochte keine Sandwiches mehr.',
        pt: 'Ele nao gostava mais de sanduiches.',
        hi: 'उसे अब सैंडविच पसंद नहीं थे।',
      },
    },
  ],
  7: [
    {
      id: 'l7-key',
      skill: 'riddle',
      title: TITLES.riddles,
      categoryLabel: CATEGORIES.puzzles,
      illustration: 'riddle',
      passage: {
        en: 'I have teeth, but I do not bite. I help open doors at home.',
        es: 'Tengo dientes, pero no muerdo. Ayudo a abrir puertas en casa.',
        fr: 'Jai des dents, mais je ne mords pas. J aide a ouvrir les portes a la maison.',
        de: 'Ich habe Zahne, aber ich beisse nicht. Ich helfe dabei, Turen zu offnen.',
        pt: 'Tenho dentes, mas nao mordo. Eu ajudo a abrir portas em casa.',
        hi: 'मेरे दांत होते हैं, लेकिन मैं काटता नहीं। मैं घर के दरवाजे खोलने में मदद करता हूं।',
      },
      question: {
        en: 'What am I?',
        es: 'Que soy?',
        fr: 'Que suis-je ?',
        de: 'Was bin ich?',
        pt: 'O que sou eu?',
        hi: 'मैं क्या हूं?',
      },
      correctAnswer: {
        en: 'A key.',
        es: 'Una llave.',
        fr: 'Une cle.',
        de: 'Ein Schlussel.',
        pt: 'Uma chave.',
        hi: 'एक चाबी।',
      },
      wrongAnswer: {
        en: 'A pillow.',
        es: 'Una almohada.',
        fr: 'Un oreiller.',
        de: 'Ein Kissen.',
        pt: 'Um travesseiro.',
        hi: 'एक तकिया।',
      },
    },
    {
      id: 'l7-shadow',
      skill: 'riddle',
      title: TITLES.riddles,
      categoryLabel: CATEGORIES.puzzles,
      illustration: 'riddle',
      passage: {
        en: 'I follow you on sunny days. I copy your shape, but I never speak.',
        es: 'Te sigo en los dias soleados. Copio tu forma, pero nunca hablo.',
        fr: 'Je te suis les jours ensoleilles. Je copie ta forme, mais je ne parle jamais.',
        de: 'Ich folge dir an sonnigen Tagen. Ich kopiere deine Form, aber ich spreche nie.',
        pt: 'Eu sigo voce em dias ensolarados. Copio sua forma, mas nunca falo.',
        hi: 'मैं धूप वाले दिनों में तुम्हारे पीछे आता हूं। मैं तुम्हारा आकार बनाता हूं, लेकिन कभी बोलता नहीं।',
      },
      question: {
        en: 'What am I?',
        es: 'Que soy?',
        fr: 'Que suis-je ?',
        de: 'Was bin ich?',
        pt: 'O que sou eu?',
        hi: 'मैं क्या हूं?',
      },
      correctAnswer: {
        en: 'Your shadow.',
        es: 'Tu sombra.',
        fr: 'Ton ombre.',
        de: 'Dein Schatten.',
        pt: 'Sua sombra.',
        hi: 'तुम्हारी छाया।',
      },
      wrongAnswer: {
        en: 'A sandwich.',
        es: 'Un sandwich.',
        fr: 'Un sandwich.',
        de: 'Ein Sandwich.',
        pt: 'Um sanduiche.',
        hi: 'एक सैंडविच।',
      },
    },
  ],
  8: [
    {
      id: 'l8-beads',
      skill: 'pattern',
      title: TITLES.patterns,
      categoryLabel: CATEGORIES.puzzles,
      illustration: 'pattern',
      passage: {
        en: 'A bracelet pattern goes red, blue, red, blue, red.',
        es: 'El patron de una pulsera va rojo, azul, rojo, azul, rojo.',
        fr: 'Le motif du bracelet est rouge, bleu, rouge, bleu, rouge.',
        de: 'Das Armbandmuster lautet rot, blau, rot, blau, rot.',
        pt: 'O padrao da pulseira e vermelho, azul, vermelho, azul, vermelho.',
        hi: 'कंगन का पैटर्न है लाल, नीला, लाल, नीला, लाल।',
      },
      question: {
        en: 'Which bead comes next?',
        es: 'Que cuenta viene despues?',
        fr: 'Quelle perle vient ensuite ?',
        de: 'Welche Perle kommt als Nachstes?',
        pt: 'Qual conta vem depois?',
        hi: 'अगला मनका कौन सा होगा?',
      },
      correctAnswer: {
        en: 'Blue.',
        es: 'Azul.',
        fr: 'Bleu.',
        de: 'Blau.',
        pt: 'Azul.',
        hi: 'नीला।',
      },
      wrongAnswer: {
        en: 'Green.',
        es: 'Verde.',
        fr: 'Vert.',
        de: 'Grun.',
        pt: 'Verde.',
        hi: 'हरा।',
      },
    },
    {
      id: 'l8-tiles',
      skill: 'pattern',
      title: TITLES.patterns,
      categoryLabel: CATEGORIES.puzzles,
      illustration: 'pattern',
      passage: {
        en: 'The floor tiles repeat triangle, square, triangle, square.',
        es: 'Las baldosas del piso repiten triangulo, cuadrado, triangulo, cuadrado.',
        fr: 'Les carreaux du sol repetent triangle, carre, triangle, carre.',
        de: 'Die Bodenfliesen wiederholen Dreieck, Quadrat, Dreieck, Quadrat.',
        pt: 'Os azulejos do chao repetem triangulo, quadrado, triangulo, quadrado.',
        hi: 'फर्श की टाइलें क्रम में हैं त्रिकोण, वर्ग, त्रिकोण, वर्ग।',
      },
      question: {
        en: 'Which shape should come next?',
        es: 'Que forma sigue?',
        fr: 'Quelle forme doit venir ensuite ?',
        de: 'Welche Form kommt als Nachstes?',
        pt: 'Qual forma vem a seguir?',
        hi: 'अगला आकार कौन सा होना चाहिए?',
      },
      correctAnswer: {
        en: 'Triangle.',
        es: 'Triangulo.',
        fr: 'Triangle.',
        de: 'Dreieck.',
        pt: 'Triangulo.',
        hi: 'त्रिकोण।',
      },
      wrongAnswer: {
        en: 'Circle.',
        es: 'Circulo.',
        fr: 'Cercle.',
        de: 'Kreis.',
        pt: 'Circulo.',
        hi: 'वृत्त।',
      },
    },
  ],
  9: [
    {
      id: 'l9-bench',
      skill: 'logic',
      title: TITLES.logic,
      categoryLabel: CATEGORIES.logic,
      illustration: 'logic',
      passage: {
        en: 'Three friends sit on a bench. Ben sits on the far left. Ana is not in the middle.',
        es: 'Tres amigos se sientan en una banca. Ben se sienta totalmente a la izquierda. Ana no esta en el medio.',
        fr: 'Trois amis sont assis sur un banc. Ben est tout a gauche. Ana nest pas au milieu.',
        de: 'Drei Freunde sitzen auf einer Bank. Ben sitzt ganz links. Ana sitzt nicht in der Mitte.',
        pt: 'Tres amigos estao sentados em um banco. Ben senta na ponta esquerda. Ana nao esta no meio.',
        hi: 'तीन दोस्त एक बेंच पर बैठे हैं। बेन सबसे बाईं ओर बैठा है। आना बीच में नहीं बैठी है।',
      },
      question: {
        en: 'Who is in the middle?',
        es: 'Quien esta en el medio?',
        fr: 'Qui est au milieu ?',
        de: 'Wer sitzt in der Mitte?',
        pt: 'Quem esta no meio?',
        hi: 'बीच में कौन है?',
      },
      correctAnswer: {
        en: 'Cara.',
        es: 'Cara.',
        fr: 'Cara.',
        de: 'Cara.',
        pt: 'Cara.',
        hi: 'कारा।',
      },
      wrongAnswer: {
        en: 'Ana.',
        es: 'Ana.',
        fr: 'Ana.',
        de: 'Ana.',
        pt: 'Ana.',
        hi: 'आना।',
      },
    },
    {
      id: 'l9-cups',
      skill: 'logic',
      title: TITLES.logic,
      categoryLabel: CATEGORIES.logic,
      illustration: 'logic',
      passage: {
        en: 'There are three cups: star, moon, and sun. The coin is not in the star cup. It is not in the moon cup.',
        es: 'Hay tres vasos: estrella, luna y sol. La moneda no esta en el vaso de estrella. Tampoco esta en el vaso de luna.',
        fr: 'Il y a trois gobelets : etoile, lune et soleil. La piece nest pas dans le gobelet etoile. Elle nest pas dans le gobelet lune.',
        de: 'Es gibt drei Becher: Stern, Mond und Sonne. Die Munze ist nicht im Sternbecher. Sie ist auch nicht im Mondbecher.',
        pt: 'Ha tres copos: estrela, lua e sol. A moeda nao esta no copo estrela. Tambem nao esta no copo lua.',
        hi: 'तीन कप हैं: तारा, चांद और सूरज। सिक्का तारे वाले कप में नहीं है। वह चांद वाले कप में भी नहीं है।',
      },
      question: {
        en: 'Which cup has the coin?',
        es: 'Que vaso tiene la moneda?',
        fr: 'Quel gobelet cache la piece ?',
        de: 'Welcher Becher hat die Munze?',
        pt: 'Qual copo tem a moeda?',
        hi: 'सिक्का किस कप में है?',
      },
      correctAnswer: {
        en: 'The sun cup.',
        es: 'El vaso de sol.',
        fr: 'Le gobelet soleil.',
        de: 'Der Sonnenbecher.',
        pt: 'O copo do sol.',
        hi: 'सूरज वाला कप।',
      },
      wrongAnswer: {
        en: 'The moon cup.',
        es: 'El vaso de luna.',
        fr: 'Le gobelet lune.',
        de: 'Der Mondbecher.',
        pt: 'O copo da lua.',
        hi: 'चांद वाला कप।',
      },
    },
  ],
  10: [
    {
      id: 'l10-robot',
      skill: 'challenge',
      title: TITLES.challenge,
      categoryLabel: CATEGORIES.challenge,
      illustration: 'challenge',
      passage: {
        en: 'A robot jumps 2 squares at a time. It starts on square 2 and wants to reach square 8.',
        es: 'Un robot salta 2 casillas cada vez. Empieza en la casilla 2 y quiere llegar a la casilla 8.',
        fr: 'Un robot saute de 2 cases a la fois. Il commence a la case 2 et veut atteindre la case 8.',
        de: 'Ein Roboter springt immer 2 Felder weiter. Er startet auf Feld 2 und will Feld 8 erreichen.',
        pt: 'Um robo pula 2 quadrados por vez. Ele comeca no quadrado 2 e quer chegar ao quadrado 8.',
        hi: 'एक रोबोट हर बार 2 खाने कूदता है। वह खाने 2 से शुरू करता है और खाने 8 तक पहुंचना चाहता है।',
      },
      question: {
        en: 'Which square could it land on in the middle?',
        es: 'En que casilla podria caer en el medio?',
        fr: 'Sur quelle case peut-il tomber au milieu ?',
        de: 'Auf welchem Feld konnte er in der Mitte landen?',
        pt: 'Em qual quadrado ele poderia cair no meio?',
        hi: 'बीच में वह किस खाने पर उतर सकता है?',
      },
      correctAnswer: {
        en: 'Square 4.',
        es: 'La casilla 4.',
        fr: 'La case 4.',
        de: 'Feld 4.',
        pt: 'O quadrado 4.',
        hi: 'खाना 4।',
      },
      wrongAnswer: {
        en: 'Square 5.',
        es: 'La casilla 5.',
        fr: 'La case 5.',
        de: 'Feld 5.',
        pt: 'O quadrado 5.',
        hi: 'खाना 5।',
      },
    },
    {
      id: 'l10-tools',
      skill: 'challenge',
      title: TITLES.challenge,
      categoryLabel: CATEGORIES.challenge,
      illustration: 'challenge',
      passage: {
        en: 'Lena needs a tool that can cut paper for her collage. On the table are scissors and a glue stick.',
        es: 'Lena necesita una herramienta que pueda cortar papel para su collage. En la mesa hay unas tijeras y una barra de pegamento.',
        fr: 'Lena a besoin dun outil pour couper du papier pour son collage. Sur la table, il y a des ciseaux et un baton de colle.',
        de: 'Lena braucht ein Werkzeug, mit dem sie Papier fur ihre Collage schneiden kann. Auf dem Tisch liegen eine Schere und ein Klebestift.',
        pt: 'Lena precisa de uma ferramenta para cortar papel para sua colagem. Na mesa ha uma tesoura e uma cola em bastao.',
        hi: 'लीना को अपने कोलाज के लिए कागज काटने वाला औजार चाहिए। मेज पर कैंची और गोंद की स्टिक रखी हैं।',
      },
      question: {
        en: 'Which item should Lena choose?',
        es: 'Que objeto debe elegir Lena?',
        fr: 'Quel objet Lena doit-elle choisir ?',
        de: 'Welchen Gegenstand sollte Lena wahlen?',
        pt: 'Qual item Lena deve escolher?',
        hi: 'लीना को कौन सी चीज चुननी चाहिए?',
      },
      correctAnswer: {
        en: 'The scissors.',
        es: 'Las tijeras.',
        fr: 'Les ciseaux.',
        de: 'Die Schere.',
        pt: 'A tesoura.',
        hi: 'कैंची।',
      },
      wrongAnswer: {
        en: 'The glue stick.',
        es: 'La barra de pegamento.',
        fr: 'Le baton de colle.',
        de: 'Den Klebestift.',
        pt: 'A cola em bastao.',
        hi: 'गोंद की स्टिक।',
      },
    },
  ],
}

function localize(text: LocalizedText, language: LanguageCode): string {
  return text[language] ?? text.en
}

function materializeCard(card: CardTemplate, language: LanguageCode): ComprehensionCard {
  return {
    id: card.id,
    skill: card.skill,
    title: localize(card.title, language),
    categoryLabel: localize(card.categoryLabel, language),
    illustration: card.illustration,
    passage: localize(card.passage, language),
    question: localize(card.question, language),
    correctAnswer: localize(card.correctAnswer, language),
    wrongAnswer: localize(card.wrongAnswer, language),
  }
}

export const LEVELS = Object.keys(LEVELS_DATA).map(Number)

export function getLevelLabel(level: number, language: LanguageCode): string {
  return localize(LEVEL_LABELS[level] ?? LEVEL_LABELS[1], language)
}

export function getCardLabel(id: string, language: LanguageCode): string {
  for (const cards of Object.values(LEVELS_DATA)) {
    const card = cards.find((item) => item.id === id)
    if (card) return localize(card.question, language)
  }
  return id
}

export function generateRound(
  level: number,
  language: LanguageCode,
  stats: ProblemStatsMap = {},
  previousCardId?: string,
): QuestionRound {
  const pool = LEVELS_DATA[level] ?? LEVELS_DATA[1]
  const previous = previousCardId ? pool.find((card) => card.id === previousCardId) : undefined
  const template = pickWeighted(pool, stats, previous)
  const card = materializeCard(template, language)
  const correctSide = Math.random() < 0.5 ? 'left' : 'right' as const

  return {
    card,
    correctSide,
    leftOption: correctSide === 'left' ? card.correctAnswer : card.wrongAnswer,
    rightOption: correctSide === 'right' ? card.correctAnswer : card.wrongAnswer,
  }
}
